# -*- coding: utf-8 -*-
"""Unimke  Nathan csc110_YOLO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IUffYCzjLYZ2tMsZpvm239Yn30GIygO5
"""

# Cell 1: Install the ultralytics library (this gives us YOLO)
!pip install ultralytics -q

# Cell 2: Upload an image from your computer into Colab
from google.colab import files

uploaded = files.upload()

# ============================================================
# Cell 3 — CSC 110 Lab: Object Detection with YOLO
# ============================================================

# Step A: Import the YOLO class from the ultralytics library
from ultralytics import YOLO

# Step B: Load the YOLO model
# "yolov8n.pt" is the smallest (and fastest) version of YOLO
# The "n" stands for "nano" - great for beginners!
# The first time you run this, it will download the model automatically.
model = YOLO("yolov8n.pt")

# Step C: Run object detection on your image
# ⚠️ Replace "your_photo.jpg" with the exact filename you uploaded in Cell 2
results = model("my_photo3.jpg")

# Step D: Print the results in a readable way
print("\n========== DETECTION RESULTS ==========")

# Loop through each result (there is usually just one for a single image)
for result in results:

    # Get the list of detected objects
    boxes = result.boxes

    # Check if anything was detected
    if len(boxes) == 0:
        print("No objects were detected in the image.")
    else:
        print(f"Number of objects detected: {len(boxes)}\n")

        # Loop through each detected object
        for i, box in enumerate(boxes):

            # Get the class ID (a number that represents the object type)
            class_id = int(box.cls)

            # Get the name of the detected object (e.g., "person", "car")
            object_name = result.names[class_id]

            # Get the confidence score (how sure the model is, from 0 to 1)
            confidence = float(box.conf)

            # Convert confidence to a percentage
            confidence_percent = confidence * 100

            # Print the result for this object
            print(f"Object {i+1}: {object_name}")
            print(f"   Confidence: {confidence_percent:.1f}%")
            print()

print("========================================")
print("Lab complete! Great job!")

# Cell 4 (Bonus): Save and display the annotated image inside Colab
from IPython.display import Image as IPImage

# Save the result image with boxes drawn on it
results[0].save(filename="output_image.jpg")

# Display it directly inside the notebook
IPImage("output_image.jpg")

# Cell 2: Upload an image from your computer into Colab
from google.colab import files

uploaded = files.upload()

# ============================================================
# Cell 3 — CSC 110 Lab: Object Detection with YOLO
# ============================================================

# Step A: Import the YOLO class from the ultralytics library
from ultralytics import YOLO

# Step B: Load the YOLO model
# "yolov8n.pt" is the smallest (and fastest) version of YOLO
# The "n" stands for "nano" - great for beginners!
# The first time you run this, it will download the model automatically.
model = YOLO("yolov8n.pt")

# Step C: Run object detection on your image
# ⚠️ Replace "your_photo.jpg" with the exact filename you uploaded in Cell 2
results = model("my_photo4.jpg")

# Step D: Print the results in a readable way
print("\n========== DETECTION RESULTS ==========")

# Loop through each result (there is usually just one for a single image)
for result in results:

    # Get the list of detected objects
    boxes = result.boxes

    # Check if anything was detected
    if len(boxes) == 0:
        print("No objects were detected in the image.")
    else:
        print(f"Number of objects detected: {len(boxes)}\n")

        # Loop through each detected object
        for i, box in enumerate(boxes):

            # Get the class ID (a number that represents the object type)
            class_id = int(box.cls)

            # Get the name of the detected object (e.g., "person", "car")
            object_name = result.names[class_id]

            # Get the confidence score (how sure the model is, from 0 to 1)
            confidence = float(box.conf)

            # Convert confidence to a percentage
            confidence_percent = confidence * 100

            # Print the result for this object
            print(f"Object {i+1}: {object_name}")
            print(f"   Confidence: {confidence_percent:.1f}%")
            print()

print("========================================")
print("Lab complete! Great job!")

# Cell 4 (Bonus): Save and display the annotated image inside Colab
from IPython.display import Image as IPImage

# Save the result image with boxes drawn on it
results[0].save(filename="output_image.jpg")

# Display it directly inside the notebook
IPImage("output_image.jpg")